### ISSUE TITLE
Display in vscode

### ISSUE THREAD

**Issue by ZenanH** [JuliaComputing/PlotlyLight.jl#10]
PlotlyLight.jl is great!

Can I display figures directly in vscode interactively instead of opening the browser?

**Comment by joshday** [comment]
Thanks!  Probably?  I'm not sure what I need to hook into to get that working.  But it would be cool if it did, so I'll look into it when I find some time.

**Comment by joshday** [comment]
Update: just need to support the `juliavscode/html` mime type.  Should get to that this week.

**Comment by joshday** [comment]
Fixed.  New release on the way.
