### ISSUE TITLE
plolty version

### ISSUE THREAD

**Issue by disberd** [JuliaComputing/PlotlyLight.jl#11]
Hello!

Very cool package for minimizing TTF plot!
I have been playing around a lot with plotly and also started working recently on wrapping around PlotlyBase.jl to optimize plotting in Pluto with plolty (https://github.com/JuliaPluto/PlutoPlotly.jl)

I might consider using your package instead of PlotlyBase.jl as base, or even try to see if I can get to add some Pluto-specific optimizations as PR to this if the concept is OK with you and they are light enough!

Apart from this introduction, I was going through your code and noticed that at least for the CDN show option which is the default, you are pointing to `plotly-latest` for the plotly version.
I do not know if this was a deliberate choice to keep the library to version 1, but since plotly moved to version 2, one has to manually specify the version number and `plolty-latest` will always point to the last revision of version 1, as written here:
https://github.com/plotly/plotly.js#un-minified-versions-are-also-available-on-cdn

> Please note that as of v2 the "plotly-latest" outputs (e.g. https://cdn.plot.ly/plotly-latest.min.js) will no longer be updated on the CDN, and will stay at the last v1 patch v1.58.5. Therefore, to use the CDN with plotly.js v2 and higher, you must specify an exact plotly.js version.

Would it be difficult to add some config parameter to also specify the plotly version to load? As quite a few fixes and features addition have happened since 1.58.5

**Comment by joshday** [comment]
I had no idea about `plotly-latest` being pinned to an old version!  Thanks for letting me know.  Feel free to give some Pluto-focused PRs!  

> Would it be difficult to add some config parameter to also specify the plotly version to load?

That should be straightforward to implement.  I also want the default to be the most recent release.
