### ISSUE TITLE
Issues with traces types that accepts matrices as inputs

### ISSUE THREAD

**Issue by disberd** [JuliaComputing/PlotlyLight.jl#12]
Some plotly trace types accepts input data in matrix format and the behavior of the trace changes whether the data is specified as a matrix or as a play 1D vector.

The issue comes from the serialization of JSON3 that by defaults serializes any ND-Array as its 1D content.

This can create issues that are different depending on the specific trace affected. I could identify the following problems in these traces, with some details in the examples below:
- `heatmap` 
- `surface`
- `contour`

# Heatmap Example

The `heatmap` trace can accept the `z` values as a matrix, in which case the `x` and `y` values can be provided as the vectors generating the underlying grid. 
If `z` is provided as a vector, `x` and `y` also has to be provided as 1D vectors containing the x/y values of each single point in z.
This creates an issue when trying to provide `z` as matrix and `x`,`y` as generating vectors in PlolyLight:

![image](https://user-images.githubusercontent.com/12846528/158834307-ae536439-3d26-487d-9c6d-078e6afd693e.png)

# Surface Example

A different problem happens in `surface` still when trying to provide `x` and `y` as generating vectors, where no Plot is produced with PlotlyLight:

![image](https://user-images.githubusercontent.com/12846528/158834536-0a6c619d-65fd-46d7-b68c-c576f5420483.png)

# Contour Example

Finally, something very weird that I don't understand happens with `contour`. The plot is rendered but the resulting contour is not the correct one:

![image](https://user-images.githubusercontent.com/12846528/158835141-cd27f438-a746-48a3-b0a5-53fe8563fd2e.png)

**Comment by disberd** [comment]
Some relevant issues I just found:
https://github.com/plotly/Dash.jl/issues/161
https://github.com/quinnj/JSON3.jl/issues/196

**Comment by joshday** [comment]
Thanks for the issue and the links!

An ugly workaround is `collect(eachrow(z))` (or maybe it's `eachcol`?).

I'd prefer that PlotlyLight didn't need to do special processing on its inputs, but that may be unavoidable.

**Comment by disberd** [comment]
Another option apart from what discussed in https://github.com/joshday/EasyConfig.jl/issues/6 could be to have a processing function here before writing the Plot object to JSON like in PlotlyBase: https://github.com/sglyon/PlotlyBase.jl/blob/2a5c8b87679ced5af7ac3894950ef0ea845eaa61/src/json.jl#L6-L11

Though that is probably what you had in mind with the *processor* thing in https://github.com/joshday/EasyConfig.jl/issues/6

**Comment by joshday** [comment]
I've added a utility function (looking at the examples in https://plotly.com/javascript/heatmaps/, it seems rows is correct):

```Julia
collectrows(x::AbstractMatrix) = collect.(eachrow(x))
```

and docs in the README as to why this is necessary.  

I think I'm ready to close this issue, as this is just an unfortunate consequence of JSON not having multidimensional arrays.  If additional edge cases crop up, we can go the processing function route.

**Comment by disberd** [comment]
Yeah `eachrow` seems indeed to be the correct one. I am also closing this as you mentioned

**Comment by StreetLevel** [comment]
Hello there,

you could add the workaround for `PlotlyJS.table`, as well. Same issue with Matrices appears here, too.

Greetz Max

**Comment by StreetLevel** [comment]
Funnily, for me 

```julia
collectcols(x::AbstractMatrix) = collect.(eachcol(x))
```

works for tables...but better doublecheck...

**Comment by joshday** [comment]
Yeah, looks like it works out of the box as long as the table implements `eachcol`!
