### ISSUE TITLE
No plot shows up

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaComputing/PlotlyLight.jl#18]
On windows. PlotlyLight v0.6.2:

When I plot, a command window opens up with this message:
![image](https://user-images.githubusercontent.com/9855832/229297137-856710ad-84e7-4984-8f77-56d3c621f4f6.png)

When I look at the mentioned file with a web browser, there is an actual plot:
![image](https://user-images.githubusercontent.com/9855832/229297283-1abd696a-265f-4ee8-89a2-b8662cd449b5.png)

I expected the plot to open in a browser by default.

**Comment by joshday** [comment]
It would be a Cobweb issue.
