### ISSUE TITLE
New tab for each plot

### ISSUE THREAD

**Issue by bdch1234** [JuliaComputing/PlotlyLight.jl#19]
Is it possible to have the plots show up in new tabs when displaying from a notebook? As it is now each new plot overwrites existing. I am on Apple silicon and running from VSCode notebook interface, if that matters.

**Comment by joshday** [comment]
A quick workaround is something like this where changing `i` will open a new tab:

```julia
i = 1
DefaultApplication.open(Cobweb.save(Cobweb.Page(plot), "myplot$i.html"))
```

but there should be a simpler way to do this.

**Comment by joshday** [comment]
Cobweb.jl now exports `Tab` ( alongside `Page`) so that `Tab(myplot)` will open a new tab (or possibly window depending on your browser's settings).
