### ISSUE TITLE
Use latest release of plotly.js

### ISSUE THREAD

**Issue by Dx-Wang** [JuliaComputing/PlotlyLight.jl#21]
Plotly.js recently [released v2.22](https://github.com/plotly/plotly.js/releases/tag/v2.22.0), which includes a new feature that I want to use. Is there a way to specify the version of plotly.js to use with this package?

**Comment by joshday** [comment]
There isn't currently a way to use a different version of Plotly, but I'd like to change that.

**Comment by joshday** [comment]
On master I've updated the version to v2.22.  I've also added the ability to use whatever src/cdn you want via:

```Julia
PlotlyLight.src!(:custom)

PlotlyLight.custom_src!("https://cdn.plot.ly/plotly-2.20.0.min.js")
```

I'll have a new release out soon.

**Comment by Dx-Wang** [comment]
That's awesome! Thanks for the quick response!
