### ISSUE TITLE
Unicode text isn't shown correctly with long series

### ISSUE THREAD

**Issue by Dx-Wang** [JuliaComputing/PlotlyLight.jl#22]
Unicode text in axis title or legend isn't shown correctly with long series. For example, the yaxis title isn't rendered correctly with the code below.
```julia
Plot(
    Config(y=rand(20000)),
    Config(
        yaxis=Config(title="H₂ η ρ")
    )
)
```

![image](https://github.com/JuliaComputing/PlotlyLight.jl/assets/6644934/341efa31-59d3-41e7-bf9c-af4c13ffa83b)

I tried similar plots with Plotly.js directly and it worked, so it doesn't seem like an upstream issue.

```js
Plotly.newPlot('graph', [{
  y: Array.from({length: 100000}, () => Math.random()),
}],{
  yaxis: {
    title: "H₂ η ρ"
  }
})
```
![image](https://github.com/JuliaComputing/PlotlyLight.jl/assets/6644934/797ecc04-ea4c-424d-9a8b-f637c787d619)

**Comment by joshday** [comment]
Thanks for the report!  Fixed on master.  New release soon.
