### ISSUE TITLE
VSCode Notebook - opens browser instead of cell rendering

### ISSUE THREAD

**Issue by rbeeli** [JuliaComputing/PlotlyLight.jl#27]
If I run the Quickstart example from your README in a VSCode notebook directly (`ipynb`), it opens a html file in the local webbrowser instead of rendering it inside the cell as output (`file:///home/XXXXXX/.julia/scratchspaces/ec354790-cf28-43e8-bb59-b484409b7bad/CobWeb/index.html`).

Any idea why? I suppose this is not the expected behaviour? I would expect the chart to get rendered inside the notebook in the cell output by default without any special configuration.

Using **VSCode 1.78.2** on **Ubuntu 22.04** with extension **Jupyter Notebook Renderers v1.0.15** installed. **Julia 1.9.0**.

Otherwise, love the idea of having a slim interface using the JavaScript API of Plotly! This should give the best performance and little maintenance required form the package side.

**Comment by joshday** [comment]
Hmm, works for me on the latest release.

- Are you able to reproduce it in a standard Jupyter notebook (not using VSCode)?
- What version of PlotlyLight.jl do you have installed?

<img width="1026" alt="Screenshot 2023-06-04 at 7 57 52 PM" src="https://github.com/JuliaComputing/PlotlyLight.jl/assets/8075494/cf6a3d28-00e2-42d6-b31c-ba11e9f77750">

**Comment by rbeeli** [comment]
Inside **jupyter lab Version 3.4.5**, I get a blank output if I end the cell with just `p`, and `display(p)` opens the html in a new tab again. **PlotlyLight v0.6.4**

**Comment by joshday** [comment]
Ah okay, I can reproduce it in Jupyterlab but not a Jupyter notebook.  Looking into it...

**Comment by joshday** [comment]
Okay, got a fix on master.  Release will be coming soon.

The best solution seems to be to bypass Jupyter's external JS loading mechanism and output an `<iframe>` that holds the plot.

**Comment by rbeeli** [comment]
If I read the code you committed correctly, you give the `iframe` a fixed height of `400px`, is that correct? Expectation would be that the size is determined by the plot itself.

**Comment by asbisen** [comment]
Is the `main` supposed to work on JupyterLab 4.0.2?

```julia
t1 = Config(x=1:10, y=rand(10), type="scatter", name="trace1")
t2 = Config(x=1:10, y=rand(10), type="scatter", name="trace2")

traces = [t1, t2]
layout = Config(title="This is the title")
config = Config(responsive=true)
p=Plot(traces, layout, config) 
p
```

I get the raw object
```
Plot(Config[Config(:x => 1:10, :y => [0.7488265320481535, 0.3614294292752763, 0.7663333792597099, 0.0048469577717829004, 0.09308451201203904, 0.4136178022429814, 0.007474039598755033, 0.4942772909692864, 0.6734583973312189, 0.749487417628091], :type => "scatter", :name => "trace1"), Config(:x => 1:10, :y => [0.5272642999877133, 0.6382787414456877, 0.6773755167551602, 0.592146611811357, 0.11496326393103617, 0.6206251298572203, 0.3853370871611915, 0.0012653593110769634, 0.017505461053807014, 0.5061343725041948], :type => "scatter", :name => "trace2")], Config(:title => "This is the title"), Config(:responsive => true), "b7at1kNXyl", Cobweb.Javascript("console.log(\"plot created!\")"))
```

and `display(p)` opens the html in a new window.

**Comment by joshday** [comment]
@asbisen what version of PlotlyLight do you have installed?
