### ISSUE TITLE
Downloading Plotly.js error

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaComputing/PlotlyLight.jl#31]
This is new (wit Julia 1.9.0 and 1.9.2):
```
[ Info: PlotlyLight: Downloading Plotly.js v2.24.3                                                                                                                                                                                 
ERROR: LoadError: InitError: RequestError: HTTP/1.1 403 Forbidden while requesting https://cdn.plot.ly/plotly-2.24.3.min.js      
```

**Comment by joshday** [comment]
Hmm, that version doesn't exist yet:  https://github.com/plotly/plotly.js/releases

What was the code that produced it?

**Comment by PetrKryslUCSD** [comment]
I've tried to bring in PlotlyLight 0.7.0. This is the error that came up.

**Comment by joshday** [comment]
Ah, sorry.  The code is checking the Plotly.js repo's tags (instead of releases) to determine the latest version.

Fixed on master.  Release out soon.
