### ISSUE TITLE
Plots in VSCode Jupyter notebook opens in browser instead of below cell

### ISSUE THREAD

**Issue by Titas22** [JuliaComputing/PlotlyLight.jl#34]
Hi,

I'm trying to use the example plot script, however I end up with the plot opening up in the browser instead of below the cell in Jupyter notebook in VSCode.

``` Julia
using PlotlyLight

p = Plot(x = 1:20, y = cumsum(randn(20)), type="scatter", mode="lines+markers")  # Make plot

display(p)
```

The output of that is:
```
Process(`'C:\WINDOWS\system32\cmd.exe' /c start '%USERPROFILE%\.julia\scratchspaces\ec354790-cf28-43e8-bb59-b484409b7bad\CobWeb\index.html'`, ProcessRunning)
```

Running the same code in REPL creates the plot in a window withing VSCode which is how I would expect it to behave.

I'm running on Windows:
Julia v1.9.0
VSCode v1.82.3
PlotlyLight v0.7.4

**Comment by joshday** [comment]
Hmm, that's a little surprising.  What happens if you remove the `display(p)` part of the cell?

**Comment by Titas22** [comment]
> Hmm, that's a little surprising. What happens if you remove the `display(p)` part of the cell?

No change, still opens up the browser. Think I might have left it in there after trying different stuff out to get it to work 😅

**Comment by joshday** [comment]
Okay, can you try running `PlotlyLight.Preset.PlotContainer.iframe!()` before the plot cell?  Does that fix it?

**Comment by Titas22** [comment]
> PlotlyLight.Preset.PlotContainer.iframe!()

Doesn't fix it. Still plots in the browser but now in a frame

**Comment by joshday** [comment]
My guess here is that there is an upstream issue, since this doesn't display anything: 

```Julia
HTML(repr("text/html", Plot(x=1:10)))
```

It's possible that VSCode's Jupyter disables the javascript that the plot's show method depends on.

**Comment by Titas22** [comment]
> ```julia
> HTML(repr("text/html", Plot(x=1:10)))
> ```

Actually, this one worked:
![image](https://github.com/JuliaComputing/PlotlyLight.jl/assets/66130422/9ff4503c-1296-479e-9edf-2dd64bdb7260)

**Comment by Titas22** [comment]
> > ```julia
> > HTML(repr("text/html", Plot(x=1:10)))
> > ```
> 
> Actually, this one worked: ![image](https://user-images.githubusercontent.com/66130422/283203534-9ff4503c-1296-479e-9edf-2dd64bdb7260.png)

Although, tried it on another machine and as you said it did nothing (same versions of PlotlyLight and Julia, but VSCode 1.84.1)

**Comment by joshday** [comment]
I think it works if you run `Preset.PlotContainer.iframe!()`, but PlotlyLight isn't (yet) able to determine that it should do this automatically if you're running inside a VSCode Jupyter notebook.

**Comment by Titas22** [comment]
You're right, but I swear it worked without it on the other machine after kernel restart. Not on this one though.

**Comment by Titas22** [comment]
Think you might be able to use `isdefined(Main, :VSCodeServer)` to check if it's running from VSCode. It does return true both from REPL and Jupyter notebooks though

**Comment by Titas22** [comment]
HI @joshday, the above pull request above solves this for me in VSCode (and still works correctly in REPL), I don't have a way to test it on other systems but don't see why it would break anything. Could you review and merge it if you're happy please?

**Comment by joshday** [comment]
Same as the other issue: PR is in your own fork and not here.
