### ISSUE TITLE
Can't generate plot in Documenter.jl

### ISSUE THREAD

**Issue by putianyi889** [JuliaComputing/PlotlyLight.jl#42]
When I use this package in an [`@example` block](https://documenter.juliadocs.org/stable/man/syntax/#@example-block), no output is rendered.

I would prefer this package over Plots.jl since it saves Github Actions time.

**Comment by putianyi889** [comment]
https://github.com/disberd/PlotlyDocumenter.jl

**Comment by joshday** [comment]
I'd like to get this working without PlotlyDocumenter, so I'm re-opening the issue

**Comment by joshday** [comment]
Fixed on master.  New release on the way.
