### ISSUE TITLE
v0.11 breaks precompilation of depent packages

### ISSUE THREAD

**Issue by marius311** [JuliaComputing/PlotlyLight.jl#51]
If your package Foo depends on PlotlyLight then because of 

https://github.com/JuliaComputing/PlotlyLight.jl/commit/ed2bc3c03978db7ec20aaf27a93682838c9a1d00#diff-607aa798775b3d7a27ebf3f1388885aa1700f02024b6e97bf56a157fadd08326R15-R21

you get 

```
Failed to precompile Foo [9ce808a0-219e-4859-ab2b-09515ef07fa1] to "/Users/marius/.julia/compiled/v1.11/Foo/jl_TkvSg1".
ERROR: LoadError: InitError: Evaluation into the closed module `PlotlyLight` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `PlotlyLight` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ ./boot.jl:430 [inlined]
  [2] __init__()
    @ PlotlyLight ~/.julia/packages/PlotlyLight/5gUUf/src/PlotlyLight.jl:19
```

I think used to be a warning (I'm not sure) but it certainly appears to be an error in Julia 1.11. This seems related too: https://github.com/JuliaLang/julia/issues/39648

**Comment by joshday** [comment]
Thank for the issue!  Fixed on master.  Release coming in a moment.

**Comment by marius311** [comment]
Thanks for the quick fix! One other small thing just gonna comment here since its so small I think there's a missing `::Plot` on https://github.com/JuliaComputing/PlotlyLight.jl/blob/accb03dda8d6b2faeac75178b4aad105c9c7c70f/src/PlotlyLight.jl#L158 which leads to everything in vscode being sent to the plot pane.
